package com.OrderService.OrderService.entity;

import jakarta.persistence.*;
import lombok.*;

@Entity
@Table(name = "Orders") // Specifies the name of the database table
@NoArgsConstructor // Lombok annotation to generate a no-argument constructor
@AllArgsConstructor // Lombok annotation to generate a constructor with all arguments
@Setter // Lombok annotation to generate setter methods for all fields
@Getter // Lombok annotation to generate getter methods for all fields
@ToString // Lombok annotation to generate the toString() method
public class Order {

    @Id // Marks the primary key of the entity
    @GeneratedValue(strategy = GenerationType.AUTO) // Specifies automatic generation of the primary key
    private Long id; // Primary key

    private String bookid; // Attribute to store the book ID
    private String customername; // Attribute to store the customer name

    // Constructor with arguments omitted for brevity

    // Getter and setter methods generated by Lombok
}
